# Generated by Django 4.0.3 on 2022-05-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoatDisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100000)),
                ('symptoms', models.CharField(max_length=100000)),
                ('prevention', models.CharField(max_length=100000)),
                ('sym', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='GoatSym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=1000)),
                ('imageurl', models.URLField()),
            ],
        ),
    ]
