# Generated by Django 4.0.3 on 2022-05-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenDisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100000)),
                ('symptoms', models.CharField(max_length=100000)),
                ('prevention', models.CharField(max_length=100000)),
                ('sym', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='ChickenSym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=1000)),
                ('imageurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CowDisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100000)),
                ('symptoms', models.CharField(max_length=100000)),
                ('prevention', models.CharField(max_length=100000)),
                ('sym', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='CowSym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=1000)),
                ('imageurl', models.URLField()),
            ],
        ),
    ]
