# Generated by Django 4.0.3 on 2022-06-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_chickendisinfo_chickensym_cowdisinfo_cowsym'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_id', models.IntegerField()),
                ('name', models.CharField(max_length=100000)),
                ('info', models.CharField(max_length=10000000)),
                ('imagelink', models.CharField(max_length=10000000)),
            ],
        ),
    ]
