# Generated by Django 4.0.3 on 2022-07-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_animalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatDisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100000)),
                ('symptoms', models.CharField(max_length=100000)),
                ('prevention', models.CharField(max_length=100000)),
                ('sym', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='CatSym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=1000)),
                ('imageurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DogDisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100000)),
                ('symptoms', models.CharField(max_length=100000)),
                ('prevention', models.CharField(max_length=100000)),
                ('sym', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='DogSym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=1000)),
                ('imageurl', models.URLField()),
            ],
        ),
    ]
